pipeline:
  install:
    image: node
    commands:
      - npm install
  build:
    image: node
    commands:
      - npm run build
  lint:
    image: node
    commands:
      - npm run lint
  test:
    image: node
    commands:
      - npm run verify

when:
  event:
    - push
    - pull_request
    - tag
