pipeline:
  install:
    image: node
    commands:
      - yarn install
  build:
    image: node
    commands:
      - yarn build
  lint:
    image: node
    commands:
      - yarn lint
  test:
    image: node
    commands:
      - yarn verify

when:
  event:
    - push
    - pull_request
    - tag
